language: bash

before_install:
                - sudo apt-get update
                - sudo apt-get install gsfonts
script:
                - bash task1.sh -h
                - bash task1.sh -f task1_images -q 1M 1280 1280 80
                - bash task1.sh -f task1_images/1.jpg -r 50%x50%
                - bash task1.sh -f task1_images -w Xudongyue
                - ls task1_images/
                - bash task1.sh -f task1_images -a -p pre
                - ls task1_images/
                - bash task1.sh -f task1_images -a -s suf
                - ls task1_images/
                - bash task1.sh -f task1_images -j
                - ls task1_images/

notifications:
                email:
                        on_success: never

