language: bash

before_install:
        - sudo apt-get updata
        - sudo apt-get install -y shellcheck
        - sudo apt-get install imagemagick
script:
        - bash task1.sh -h

notifications:
        email:
                on_success: never
